# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Idan Bidani
title: DevOps Manager
# email: iplaman@gmail.com
website: ibidani.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: idanbidani
github_username:  ibidani
stackoverflow_username: "889563"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: bidani
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: IdanBidani
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: ibidani.com
#   icon: fas fa-globe
#   url: https://ibidani.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: "images/profile.jpg"
about_content: | # this will include new lines to allow paragraphs
 Husband toğŸ¥‡, Intern Dad ğŸ‘¶ğŸ½â™€ï¸.

 Optimistic technologist. Specialist in application development and build environments, source control, infrastructure, CI/CD, quality and security. Enjoys solving problems at a large scale.
 Passionate about empowering individuals to do more with less (âŒšğŸŒ²ğŸ’¸ğŸ‘)

 I am most skilled in: <mark>Asking Quesions</mark> and <mark>Brown-White nappy deployments</mark>ğŸ’©ğŸ˜‰
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cox Communications
        link: https://www.cox.com
        link_text: cox.com
        sub_title: Manager
        caption: February 2018 - Present
        quote: >
          The third-largest cable provider in the nation, Cox Communications Inc. is noted for its high-capacity, reliable broadband delivery network and superior customer care.
        description: | # this will include new lines to allow paragraphs
            Manages the Software Configuration Management team of 5 providing DevOps services for over 100 development and operations teams. The primary purpose is to provide automation services to increase productivity for over 3,000 developers. Advocates for DevOps maturity across Cox teams by promoting a culture of high trust, empowered individuals, and customer focus in order to increase development velocity and shorten lead time. 
      - layout: left
        # title: Cox Communications
        link: https://www.cox.com
        link_text: cox.com
        sub_title: Software Configuration Manager
        caption: September 2013 - February 2018
        description: | # this will include new lines to allow paragraphs
            Lead engineer of the Software Configuration Management team. Supplied source control, automated compiling, deploying, and testing to support application development and operations teams. 
            Introduced and rolled out (CI) Continuous Integration pipelines to Cox as part of its Digital Transformation initiative Maintained a large-scale CI/CD Jenkins environment generating a daily average of 550 automated activities (builds, deployments, tests) facilitating 3,975 releases in 2018
      - layout: left
        title: SAP Labs, Israel
        link: https://www.sap.com/about/company/office-locations/israel.html
        link_text: sap.com
        sub_title: DevOps Engineer
        caption: February 2010 - July 2013
        quote: >
          The R&D center in Israel, usually referred to as SAP Labs Israel, is one of the global strategic development centers for SAP.
        description: | # this will include new lines to allow paragraphs
            Development Operations Engineer of SAP Portal Cloud solution, SAP Social Intelligence and SAP Business Objects supporting over 80 developers. Specialist in development and build environment, source control, infrastructure configuration, Continuous Integration and quality control in Agile environment.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology some of my other interests and hobbies are:
      - Spending time with my dearest [Joanna Bidani](https://jbidani.com) and our daughter
      - Friends time
      - Playing the piano - Yamaha P-125
      - Hacking Home Automation Using [Home Assistant](https://www.home-assistant.io)
      - Traveling Earth (for now...) - Israel, United States, Germany, Canada, Scotland, England, Ireland, Thailand, Japan, France
      - Running + Biking

      
# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag